app:
  name: Otuken3D
  version: 0.1.0
  description: 3B Model İşleme API

server:
  host: 0.0.0.0
  port: 8000
  workers: 4
  timeout: 60

storage:
  upload_dir: uploads
  output_dir: outputs
  temp_dir: temp
  max_file_size: 104857600  # 100MB

processing:
  max_vertices: 100000
  max_faces: 50000
  texture_size: 2048
  texture_quality: 90

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/otuken3d.log

security:
  allowed_formats: [".obj", ".stl", ".ply", ".glb", ".gltf", ".fbx", ".dae"]
  allowed_origins: ["*"]
  max_batch_size: 10 