# Model Konfigürasyonu
model:
  cultural_vocab_size: 10000  # Türkçe ve kültürel terimleri için
  embedding_dim: 512
  hidden_dim: 1024
  num_layers: 12
  dropout: 0.1

# Eğitim Parametreleri
training:
  learning_rate: 0.0001
  batch_size: 32
  num_epochs: 100
  save_interval: 5
  num_workers: 4
  
# Veri Seti Ayarları
dataset:
  root_dir: "data"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  
# Dönüşümler
transforms:
  normalize: true
  random_rotate: true
  random_scale: [0.8, 1.2]
  num_points: 2048

# Checkpoint Ayarları
checkpoint:
  dir: "models/checkpoints/otuken3d"
  save_best_only: true
  monitor: "val_loss"
  
# Kültürel Özelleştirme
cultural:
  language: "tr"
  special_tokens:
    - "motif"
    - "desen"
    - "süsleme"
    - "bezeme"
  style_categories:
    - "Göktürk"
    - "Selçuklu"
    - "Osmanlı"
    - "Anadolu" 