apiVersion: v1
kind: Service
metadata:
  name: otuken3d
  labels:
    app: otuken3d
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: otuken3d 