model:
  name: "otuken3d_image2shape"
  version: "1.0.0"
  base_model: "point-e"
  language: "tr"
  image_encoder: "resnet50"
  
architecture:
  embedding_dim: 512
  hidden_dim: 1024
  num_layers: 12
  num_heads: 8
  dropout: 0.1
  
image_processing:
  input_size: 224
  normalize: true
  augmentation:
    enabled: true
    color_jitter: 0.4
    random_crop: true
    random_flip: true
    
training:
  batch_size: 32
  learning_rate: 0.0001
  warmup_steps: 1000
  max_epochs: 100
  
generation:
  num_points: 2048
  temperature: 0.8
  top_k: 40
  top_p: 0.95 